

---
engine: terraform
input:
  - OS_USERNAME
  - OS_PASSWORD
  - OS_AUTH_URL
  - OS_PROJECT_NAME
output:

  - instance_server_public_key_user1
  - instance_server_private_key_user1

  - instance_ip_OracleDB
  - instance_ip_gestaut_vm
  - instance_ip_elasticsearch_vm
  - instance_ip_edi_vm

...
